# Generated by Django 6.1.1 on 2026-09-19 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.TextField()),
                ('input_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('awaiting_approval', 'Awaiting Approval'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=32)),
                ('messages', models.JSONField(default=list)),
                ('pending', models.JSONField(default=list)),
                ('llm_calls', models.IntegerField(default=0)),
                ('final_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('thought', 'Thought'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result'), ('approval', 'Approval'), ('final', 'Final'), ('error', 'Error')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent.run')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
