# Generated by Django 6.1.1 on 2026-09-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
